/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package global.goit.edu;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Human denis = new Human("Denis", "Bunak");
        Gson json = new GsonBuilder().setPrettyPrinting().create();
        String denisJson = json.toJson(denis);
        System.out.println(denisJson);
    }
}